<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\static-html-3\**" />
    <Compile Remove="wwwroot\static-html\**" />
    <Compile Remove="wwwroot\web\**" />
    <Content Remove="wwwroot\static-html-3\**" />
    <Content Remove="wwwroot\static-html\**" />
    <Content Remove="wwwroot\web\**" />
    <EmbeddedResource Remove="wwwroot\static-html-3\**" />
    <EmbeddedResource Remove="wwwroot\static-html\**" />
    <EmbeddedResource Remove="wwwroot\web\**" />
    <None Remove="wwwroot\static-html-3\**" />
    <None Remove="wwwroot\static-html\**" />
    <None Remove="wwwroot\web\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Shared\Services\TransactionAPIService.cs" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="CsvHelper" Version="33.1.0" />
	  <PackageReference Include="MailKit" Version="4.16.0" />
	  <PackageReference Include="Mapster" Version="10.0.7" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.6" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.6" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="MimeKit" Version="4.16.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="Plugin.BLE" Version="3.2.1" />
	  <PackageReference Include="Plugin.InAppBilling" Version="10.0.0" />
	  <PackageReference Include="SkiaSharp" Version="3.119.2" />
	  <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	  <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
  </ItemGroup>

</Project>